name: Cron Dispatcher

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  call-dispatcher:
    runs-on: ubuntu-latest
    steps:
      - name: Call dispatcher endpoint
        env:
          URL: ${{ secrets.PRODUCTION_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$URL" ] || [ -z "$CRON_SECRET" ]; then
            echo "Missing PRODUCTION_URL or CRON_SECRET secrets" >&2
            exit 1
          fi
          set -e
          echo "Calling $URL/api/admin/cron/dispatcher"
          HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" "$URL/api/admin/cron/dispatcher?secret=$CRON_SECRET")
          echo "Status: $HTTP_STATUS"
          cat response.json || true
          # Consider 2xx and 3xx as success
          if [ "$HTTP_STATUS" -lt 200 ] || [ "$HTTP_STATUS" -ge 400 ]; then
            exit 1
          fi